name: SwordArtOnline
version: 0.1-BETA
main: com.SwordArtOnline
api-version: 1.21
authors:
  - Katieey
description: >
  Sword Art Online inspired Minecraft plugin.
  Handles floors, spawns, teleportation, and advanced  mechanics.

# Commands
commands:
  tab:
    description: Manage tab list system
    usage: /tab [view|refresh|debug]
  spawn:
    description: Teleport to nearest spawn or manage spawns
    usage: /spawn [set|delete|edit]
    aliases: [sp]
    permission: .spawn.use
    permission-message: "&cYou do not have permission to use this command."
  skill:
    description: Manage  floor regions
    usage: /skill [wand|set <floor>]
    permission: .region.use
    permission-message: "&cYou do not have permission to use this command."
  region:
    description: Manage  floor regions
    usage: /region [wand|set <floor>]
    permission: .region.use
    permission-message: "&cYou do not have permission to use this command."

# Permissions
permissions:
  # Spawn permissions
  .spawn.use:
    description: Allows using /spawn to teleport to nearest spawn
    default: true
  .spawn.set:
    description: Allows setting new spawns
    default: op
  .spawn.delete:
    description: Allows deleting spawns
    default: op
  .spawn.edit:
    description: Allows editing existing spawns
    default: op
  .spawn.bypass.cooldown:
    description: Allows bypassing teleport cooldowns
    default: op

  # Region permissions
  .region.use:
    description: Allows using /region commands
    default: op
  .region.wand:
    description: Allows receiving the Region Wand
    default: op
  .region.set:
    description: Allows setting regions for floors
    default: op
