name: SwordArtOnline
version: 0.1-BETA
main: com.SwordArtOnline
api-version: 1.21
authors:
  - Katieey
description: >
  Sword Art Online inspired Minecraft plugin.
  Handles floors, spawns, teleportation, and advanced SAO mechanics.

# Commands
commands:
  spawn:
    description: Teleport to nearest spawn or manage spawns
    usage: /spawn [set|delete|edit]
    aliases: [sp]
    permission: sao.spawn.use
    permission-message: "&cYou do not have permission to use this command."

  region:
    description: Manage SAO floor regions
    usage: /region [wand|set <floor>]
    permission: sao.region.use
    permission-message: "&cYou do not have permission to use this command."

# Permissions
permissions:
  # Spawn permissions
  sao.spawn.use:
    description: Allows using /spawn to teleport to nearest spawn
    default: true
  sao.spawn.set:
    description: Allows setting new spawns
    default: op
  sao.spawn.delete:
    description: Allows deleting spawns
    default: op
  sao.spawn.edit:
    description: Allows editing existing spawns
    default: op
  sao.spawn.bypass.cooldown:
    description: Allows bypassing teleport cooldowns
    default: op

  # Region permissions
  sao.region.use:
    description: Allows using /region commands
    default: op
  sao.region.wand:
    description: Allows receiving the Region Wand
    default: op
  sao.region.set:
    description: Allows setting regions for floors
    default: op
