# =====================================================
# Spawn Teleport Task Customization
# =====================================================
# Edit this file to change teleport task behavior:
# Placeholders:
#   %spawn% - spawn name
#   %floor% - floor name
#   %seconds% - countdown seconds
#   %player% - player name
# Messages can reference default messages using [MSG]: %key%
# Titles support & color codes
# Particles can be enabled with type and count
# =====================================================

teleport-task:
  countdown:
    # The message displayed in actionbar during countdown
    actionbar: "[MSG]: %teleport-start%"
    # Optional extra message
    extra-message: "&aPrepare for teleport!"
    # Show title during countdown
    title: "&eTeleporting..."
    subtitle: "[MSG]: %teleport-start%"
    fade-in: 5
    stay: 20
    fade-out: 5
    # Particle effect
    particle:
      enabled: true
      type: "SPELL_WITCH"
      count: 10
      speed: 0.1
      offset-x: 0.5
      offset-y: 1
      offset-z: 0.5

  success:
    actionbar: "[MSG]: %teleport-success%"
    title: "&aTeleported!"
    subtitle: ""
    particle:
      enabled: true
      type: "VILLAGER_HAPPY"
      count: 5
      speed: 0.1
      offset-x: 0.5
      offset-y: 1
      offset-z: 0.5

  cancel:
    move: "[MSG]: %teleport-cancel-move%"
    damage: "[MSG]: %teleport-cancel-damage%"
