name: SwordArtOnline
version: 0.1-BETA
main: com.SwordArtOnline
api-version: 1.21
authors:
  - Katieey
description: >
  Sword Art Online inspired Minecraft plugin.
  Handles floors, spawns, teleportation, and advanced SAO mechanics.

# Commands
commands:
  spawn:
    description: Teleport to nearest spawn or manage spawns
    usage: /spawn [set|delete|edit]
    aliases: [sp]
    permission: sao.spawn.use
    permission-message: "&cYou do not have permission to use this command."

# Permissions
permissions:
  # Basic teleport
  sao.spawn.use:
    description: Allows using /spawn to teleport to nearest spawn
    default: true

  # Admin spawn management
  sao.spawn.set:
    description: Allows setting new spawns
    default: op
  sao.spawn.delete:
    description: Allows deleting spawns
    default: op
  sao.spawn.edit:
    description: Allows editing existing spawns
    default: op

  # Optional advanced permissions
  sao.spawn.bypass.cooldown:
    description: Allows bypassing teleport cooldowns
    default: op
